### ISSUE TITLE
Syntax highlighting stops working when string is assigned to a "const"

### ISSUE THREAD

**Issue by samnau** [vokeio/language-javascript-plus#1]
This plugin works great for `var` and `let` but for some reason `const` breaks the syntax highlighting

**Comment by xeaone** [comment]
I will get right on that. Thanks.

**Comment by xeaone** [comment]
I am not able to reproduce this issue. Can you share a bit of code that you found the issue with?

**Comment by samnau** [comment]
Well when I use a template string like this:
```
const htmlTemplate = `
<div>
Content
</div>
`
```
The HTML syntax highlighting stops working and it's just a normal string again. If I use it as a `var` or a `let` it still works. 

Now to be specific, I was using the the Atom grammar setting for `Javascript (Rails)`. I found a workaround by setting the grammar to `Regular Expressions (Javascript)` which allows your package to start working again. Unfortunately, I lose most of my JS highlighting that isn't part of the template string.

**Comment by xeaone** [comment]
Ah yes the variable or property name currently supported for HTML are html and template. It can also be upper or lower case . So instead of `const htmlTemplate` do `const template` or `const html`
