### ISSUE TITLE
Seems broken in 1.41.0 update

### ISSUE THREAD

**Issue by brettz9** [vokeio/language-javascript-plus#13]
In the 1.41.0 update, I get the following message in console:

> <embedded>:11 Failed to require the main module of 'language-javascript-plus' because it requires one or more incompatible native modules (tree-sitter-javascript).
> Run `apm rebuild` in the package directory and restart Atom to resolve.

...But running `apm rebuild` in the `.atom/packages/language-javascript-plus` directory or the Atom packages directory did not help avoid this message.

**Comment by brettz9** [comment]
I later saw a bug icon on the bottom of the window, and when I click that, Atom gave me a chance to rebuild the tree-sitter native package it was using. That went on and now I no longer get the bug icon (or console errors), but it still doesn't do the highlighting.

**Comment by xeaone** [comment]
Yeah I do not understand why it has to rebuild when using the tree sitter. 

Are you using the comment  `/*html*/` directly before your string?

**Comment by brettz9** [comment]
Yeah...

**Comment by xeaone** [comment]
I removed the  tree sitter dependency I think this will fix the issue. Let me know if it does not.

**Comment by brettz9** [comment]
At least in my current release of Atom, I didn't seem to have been getting the error anymore even before making the update just now, though I'm afraid I hadn't checked carefully (e.g., checking the HTML template behavior) before making the update just now to confirm it indeed would not be getting errors under other conditions. But in any case, there are no errors now, and it is showing the coloring nicely, thank you.

**Comment by xeaone** [comment]
Good to hear thanks for reporting back.
