### ISSUE TITLE
It can't install

### ISSUE THREAD

**Issue by joagostini** [vokeio/language-javascript-plus#14]
Error message when I tray to install language-javascript-plus:

C:\Users\joago>apm install language-javascript-plus
Installing language-javascript-plus to C:\Users\joago\.atom\packages failed

> tree-sitter-javascript@0.13.10 install C:\Users\joago\AppData\Local\Temp\apm-install-dir-120115-84156-scsrkj.8qcd\node_modules\language-javascript-plus\node_modules\tree-sitter-javascript
> node-gyp rebuild

C:\Users\joago\AppData\Local\Temp\apm-install-dir-120115-84156-scsrkj.8qcd\node_modules\language-javascript-plus\node_modules\tree-sitter-javascript>if not defined npm_config_node_gyp (node "C:\Users\joago\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\joago\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\joago\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\joago\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\joago\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\joago\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\joago\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\joago\AppData\Local\Temp\apm-install-dir-120115-84156-scsrkj.8qcd\node_modules\language-javascript-plus\node_modules\tree-sitter-javascript
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\joago\AppData\Local\Temp\apm-install-dir-120115-84156-scsrkj.8qcd\package.json'
npm WARN apm-install-dir-120115-84156-scsrkj.8qcd No description
npm WARN apm-install-dir-120115-84156-scsrkj.8qcd No repository field.
npm WARN apm-install-dir-120115-84156-scsrkj.8qcd No README data
npm WARN apm-install-dir-120115-84156-scsrkj.8qcd No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-javascript@0.13.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter-javascript@0.13.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joago\.atom\.apm\_logs\2020-02-15T15_24_23_644Z-debug.log

My configuration:
[2020-02-15T15_27_45_542Z-debug.log](https://github.com/vokeio/language-javascript-plus/files/4208812/2020-02-15T15_27_45_542Z-debug.log)

C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\MinGW\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64;

**Comment by xeaone** [comment]
I think 3.0.2 should resolve this issue. Let me know if it does not. Sorry for the delay.

**Comment by brettz9** [comment]
It seems I can't see any highlighting if `language-javascript` is disabled--not sure if it was due to this change or not.

**Comment by xeaone** [comment]
The grammar/language being used should be `language-javascript`. So that should not be disabled. `language-javascript-plus` works on top of the JS grammar.

**Comment by brettz9** [comment]
@vokeio : Ah yes, thank you.

But still, even with both enabled (and no language-babel which perhaps could be interfering), and having no "source.js.plus" in the config (though also with adding `source.js.plus` in addition or in place of `source.js`, I get no highlighting:

![image](https://user-images.githubusercontent.com/20234/113933655-72141f80-9827-11eb-88e3-52a5cbe9ef94.png)

**Comment by brettz9** [comment]
That shows another issue as it'd be nice to allow the linter not to flag here in allowing a space before and after, as I don't believe it did before.

**Comment by xeaone** [comment]
You should be allowed to have a space. I just tested that and it appears to work for me. Maybe there is a different package that is conflicting. Sorry for the trouble you are experiencing.

**Comment by brettz9** [comment]
Such a kind response, thank you.

FWIW, I disabled every non-core extension besides your (with every core one enabled), and still no luck. I also removed my custom stylesheet. Maybe one last thing I could try is seeing what your `config.cson` looks like for the package?

Could it be you are looking at a developer version which differs from the released?
