### ISSUE TITLE
Enhancement: Make it work for template tag literals

### ISSUE THREAD

**Issue by robhicks** [vokeio/language-javascript-plus#2]
[hyperHTML](https://viperhtml.js.org/hyperhtml/documentation/#introduction-0) - a popular library for declarative and reactive Web Applications, uses a template tag literal.
```Javascript

// bind hyperHTML to a generic DOM container
--
  | const bodyRender = hyperHTML.bind(document.body);
  |  
  | // use it to declare any layout you needed
  | bodyRender`
  | <h1>${document.title}</h1>
  | <ul>
  | ${[
  | {name: 'First item'},
  | {name: 'Second item'},
  | {name: 'Third item'}
  | ].map(item =>
  | `<li>${item.name}</li>`)}
  | </ul>
  | `;
```
It would be great if your package could support template tag literals.

**Comment by xeaone** [comment]
In progress I will let you know when they are supported.

**Comment by xeaone** [comment]
Template tags are now supported. You can also now use comments like so ```/*html*/ `<div></div>` ```

close [#dd3b89a887abd3e7464215ab0d39926bf6519815](https://github.com/AlexanderElias/language-javascript-plus/commit/dd3b89a887abd3e7464215ab0d39926bf6519815)

**Comment by robhicks** [comment]
Thanks! I'll give it a try.

**Comment by xeaone** [comment]
If I satisfied your enhancement a star would be great ;-).

**Comment by robhicks** [comment]
I haven't tried it yet, but I'm using your package now so you deserve a star.
