### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by luv2hike** [vokeio/language-javascript-plus#8]
Running Atom 1.32.0 on OS/X.

![screen shot 2019-02-11 at 11 05 58 am](https://user-images.githubusercontent.com/47532767/52575927-1f787d80-2ded-11e9-8ea0-002987ebdcaf.png)
![screen shot 2019-02-11 at 11 05 21 am](https://user-images.githubusercontent.com/47532767/52575932-20111400-2ded-11e9-9735-0fc19cdd9233.png)
![screen shot 2019-02-11 at 11 05 04 am](https://user-images.githubusercontent.com/47532767/52575934-20a9aa80-2ded-11e9-9a23-623d09505a45.png)

Better results seem to be achieved currently by simply setting the type to C# (even though I'm writing Vue Javascript).

![screen shot 2019-02-11 at 11 08 14 am](https://user-images.githubusercontent.com/47532767/52576037-5a7ab100-2ded-11e9-9bfd-0b8ac90c0080.png)

**Comment by xeaone** [comment]
The plugin no-longer looks for variable names such as css or html. You will need to prefix your template strings with a comment that contains css, html, or js. 

```js 
var template = /*html*/`
	<div>will have syntax highlighting</div>
`;
```

Make sure to star if this fixes your issue!

**Comment by luv2hike** [comment]
Yes, and that is what I already have.  My variable names also happen to be
html and css, but that should be okay?

let html = /*html*/`
    <div id="someid">
        <span>syntax?</span>
    </div>
`;

**Comment by xeaone** [comment]
Well if you have the comment prefix and it is not highlighting make sure you are using the new tree parser in the atom setting. Check that and let me know.

**Comment by luv2hike** [comment]
Thanks for the reply.
That option was off so I checked it.
Seems to have helped some with html, but still not css.
Also, I even removed the /*html*/ from the html variable and it was still
highlighted, like it made no difference.
Screen shots attached.

**Comment by xeaone** [comment]
Maybe try updating Atom. I am on 1.34.0 and don't experience those issues. Also make sure to restart atom after you enable the new syntax parser.

If you attached images I cant see it. You will need to use the github website.

**Comment by luv2hike** [comment]
Okay, the update to Atom did help some and now the tree parse setting does
make a difference.
However, I still see no difference regardless if I have the /**/ comments
or not.  The highlighting remains the same.
For the CSS block, anyway it can match the highlighting used by Atom for
standard CSS files?  It is not syntax coloring the color names (black,
blue, etc).

Thanks.

**Comment by xeaone** [comment]
Can you post an image?

**Comment by luv2hike** [comment]
Done.

https://github.com/tree-sitter/tree-sitter/issues/276
